dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_script:
  - rm -rf node_modules/ethereumjs-testrpc-sc
  - mv .travis/ethereumjs-testrpc-sc node_modules/ethereumjs-testrpc-sc
  - npm install --global typescript
  - truffle version
script:
  - npm run coverage
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls