dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_script:
  - truffle version
script:
  - npm run coverage
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls